/*
 * regions — les régions naturelles, et à quoi ressemble le pays dans chacune.
 *
 * De la **donnée sur le monde**, au même titre qu'une tuile vectorielle : ce
 * fichier dit ce qu'on trouve dans un pays, jamais de quelle couleur c'est. Un
 * mot y est une clé, que `regionInterpretation` traduit en concepts de moteur
 * et que le thème peint. Aucune valeur artistique n'a sa place ici.
 *
 * ## Le dossier
 *
 *   id       identifiant stable, en minuscules sans accent
 *   name     le nom du pays, tel qu'on le dit
 *   anchors  [[lng, lat], …] — un point au moins, posé dans l'épaisseur de la
 *            région. La région d'un lieu est celle dont une ancre est la plus
 *            proche (voir `region.js`) : une vallée, un littoral ou un couloir
 *            en demandent trois ou quatre, un plateau compact une seule.
 *   matrix   le paysage là où la carte se tait — le champ qui porte le plus
 *   stone    la géologie dominante, c'est-à-dire la couleur de la pierre
 *   building [mur, toit] — deux mots au plus, dans cet ordre
 *   farming  l'assolement, **du plus répandu au moins répandu** : le rang est
 *            l'information, il n'y a pas de poids à écrire
 *   trees    les essences dominantes, trois ou quatre
 *
 * Rien d'autre. Pas d'altitude, pas d'humidité, pas de score : ce qui existe
 * réellement à un endroit est relevé par le vectoriel, et une région qui le
 * redirait le contredirait un jour.
 *
 * ## Le vocabulaire est fermé
 *
 * Un mot hors de ces listes est une erreur, et le test la lève. Certains mots
 * ne sont pas encore rendus par le décor : ils sont admis quand même — décrire
 * l'Andalousie sans serre serait décrire autre chose — et le test les inventorie.
 * La liste qui fait foi est dans `regionInterpretation.js` ; celle-ci est
 * rappelée pour qu'on puisse remplir le fichier sans l'ouvrir.
 *
 *   matrix   hedgerow_meadow · openfield_cropland · wet_grassland · marsh ·
 *            moor_heath · broadleaf_woodland · conifer_forest · boreal_taiga ·
 *            terraced_slope · dry_scrub · garrigue · dry_steppe ·
 *            alpine_pasture · bare_rock · dune_coast · desert_stone ·
 *            desert_sand · savanna* · tropical_forest* · rice_terrace*
 *
 *   stone    limestone · chalk · granite · schist · sandstone · basalt · clay ·
 *            alluvium · gypsum · laterite* · loess*
 *
 *   building murs   light_stone · dark_stone · granite · red_brick ·
 *                   pale_brick · half_timber · whitewash · rendered · timber ·
 *                   red_timber · adobe*
 *            toits  slate_roof · flat_tile_roof · curved_tile_roof ·
 *                   stone_slab_roof · flat_roof · thatch_roof* ·
 *                   shingle_roof* · metal_roof*
 *
 *   farming  cereal · maize · sunflower · rapeseed · vineyard · orchard ·
 *            olive · almond · lavender · fallow · rice* · greenhouse* ·
 *            cotton* · sugarcane* · tea* · coffee* · oil_palm*
 *
 *   trees    oak · beech · chestnut · ash · hornbeam · alder · holm_oak ·
 *            cork_oak · birch · poplar · eucalyptus · scots_pine ·
 *            maritime_pine · aleppo_pine · black_pine · stone_pine · spruce ·
 *            fir · larch · olive · juniper · acacia* · palm*
 *
 *   (*) admis, pas encore rendu par le décor.
 *
 * ## Couverture
 *
 * France, Espagne et Royaume-Uni. Ailleurs, `regionAt` rend `null` et le décor
 * s'éteint (voir `worldComposer.refresh`) — le seul état honnête tant que le
 * pays n'est pas écrit.
 */

export const REGIONS = [
  // ---------------------------------------------------------------- France --
  {
    id: 'flandre',
    name: 'Flandre',
    anchors: [[2.6, 50.85], [3.2, 50.7]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'maize', 'fallow', 'rapeseed'],
    trees: ['poplar', 'ash', 'oak'],
  },
  {
    id: 'artois',
    name: 'Artois',
    anchors: [[2.6, 50.4]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'maize'],
    trees: ['beech', 'oak', 'ash'],
  },
  {
    id: 'boulonnais',
    name: 'Boulonnais',
    anchors: [[1.8, 50.72]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'picardie',
    name: 'Plaine picarde',
    anchors: [[2.3, 49.9], [3.3, 49.75]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'sunflower'],
    trees: ['beech', 'oak', 'poplar'],
  },
  {
    id: 'thierache',
    name: 'Thiérache',
    anchors: [[3.9, 49.93]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['red_brick', 'slate_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'alder'],
  },
  {
    id: 'pays_de_caux',
    name: 'Pays de Caux',
    anchors: [[0.7, 49.72]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'maize'],
    trees: ['beech', 'oak', 'ash'],
  },
  {
    id: 'pays_de_bray',
    name: 'Pays de Bray',
    anchors: [[1.6, 49.6]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'poplar'],
  },
  {
    id: 'pays_dauge',
    name: 'Pays d’Auge',
    anchors: [[0.2, 49.1]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['orchard', 'fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'cotentin',
    name: 'Cotentin',
    anchors: [[-1.45, 49.45], [-1.3, 49.1]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['granite', 'slate_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'alder'],
  },
  {
    id: 'bocage_normand',
    name: 'Bocage normand',
    anchors: [[-0.8, 48.85]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow', 'maize', 'cereal', 'orchard'],
    trees: ['oak', 'chestnut', 'ash'],
  },
  {
    id: 'vexin',
    name: 'Vexin',
    anchors: [[1.8, 49.15]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'sunflower'],
    trees: ['oak', 'beech', 'ash'],
  },
  {
    id: 'beauce',
    name: 'Beauce',
    anchors: [[1.7, 48.3]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'maize', 'fallow'],
    trees: ['oak', 'poplar', 'ash'],
  },
  {
    id: 'brie',
    name: 'Brie',
    anchors: [[3.05, 48.65]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'maize', 'fallow'],
    trees: ['oak', 'hornbeam', 'ash'],
  },
  {
    id: 'gatinais',
    name: 'Gâtinais',
    anchors: [[2.6, 48.1]],
    matrix: 'broadleaf_woodland',
    stone: 'sandstone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'sunflower'],
    trees: ['oak', 'scots_pine', 'birch'],
  },
  {
    id: 'champagne_craie',
    name: 'Champagne crayeuse',
    anchors: [[4.3, 48.9]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'vineyard'],
    trees: ['scots_pine', 'oak', 'beech'],
  },
  {
    id: 'champagne_humide',
    name: 'Champagne humide',
    anchors: [[4.65, 48.5]],
    matrix: 'wet_grassland',
    stone: 'clay',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'alder', 'poplar'],
  },
  {
    id: 'argonne',
    name: 'Argonne',
    anchors: [[5.0, 49.1]],
    matrix: 'broadleaf_woodland',
    stone: 'sandstone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['beech', 'oak', 'hornbeam'],
  },
  {
    id: 'ardenne',
    name: 'Ardenne',
    anchors: [[4.9, 49.82]],
    matrix: 'broadleaf_woodland',
    stone: 'schist',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['beech', 'oak', 'spruce'],
  },
  {
    id: 'lorraine',
    name: 'Plateau lorrain',
    anchors: [[6.2, 48.9], [5.6, 49.2]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'maize', 'fallow'],
    trees: ['oak', 'beech', 'hornbeam'],
  },
  {
    id: 'vosges',
    name: 'Vosges',
    anchors: [[6.9, 48.1], [7.1, 48.5]],
    matrix: 'conifer_forest',
    stone: 'sandstone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['fir', 'spruce', 'beech'],
  },
  {
    id: 'plaine_alsace',
    name: 'Plaine d’Alsace',
    anchors: [[7.6, 48.4], [7.5, 47.9]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['maize', 'cereal', 'vineyard', 'fallow'],
    trees: ['oak', 'poplar', 'ash'],
  },
  {
    id: 'jura',
    name: 'Jura',
    anchors: [[6.0, 46.8], [5.8, 47.2]],
    matrix: 'conifer_forest',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['fir', 'spruce', 'beech'],
  },
  {
    id: 'bresse',
    name: 'Bresse',
    anchors: [[5.2, 46.4]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['maize', 'cereal', 'fallow'],
    trees: ['oak', 'poplar', 'alder'],
  },
  {
    id: 'dombes',
    name: 'Dombes',
    anchors: [[5.0, 46.0]],
    matrix: 'wet_grassland',
    stone: 'clay',
    building: ['pale_brick', 'flat_tile_roof'],
    farming: ['maize', 'cereal', 'fallow'],
    trees: ['oak', 'alder', 'poplar'],
  },
  {
    id: 'bourgogne',
    name: 'Côte bourguignonne',
    anchors: [[4.8, 47.1]],
    matrix: 'broadleaf_woodland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['vineyard', 'cereal', 'fallow', 'rapeseed'],
    trees: ['oak', 'hornbeam', 'scots_pine'],
  },
  {
    id: 'morvan',
    name: 'Morvan',
    anchors: [[4.0, 47.1]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['oak', 'beech', 'spruce'],
  },
  {
    id: 'bretagne_littorale',
    name: 'Bretagne littorale',
    anchors: [[-4.3, 48.4], [-2.9, 48.65], [-3.4, 47.8]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow', 'maize', 'cereal'],
    trees: ['oak', 'maritime_pine', 'chestnut'],
  },
  {
    id: 'bretagne_interieure',
    name: 'Bretagne intérieure',
    anchors: [[-3.0, 48.1], [-2.2, 48.0]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['granite', 'slate_roof'],
    farming: ['maize', 'fallow', 'cereal'],
    trees: ['oak', 'chestnut', 'beech'],
  },
  {
    id: 'monts_arree',
    name: 'Monts d’Arrée',
    anchors: [[-3.9, 48.4]],
    matrix: 'moor_heath',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'scots_pine'],
  },
  {
    id: 'perche',
    name: 'Perche',
    anchors: [[0.8, 48.4]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'anjou',
    name: 'Anjou',
    anchors: [[-0.55, 47.45], [-0.15, 47.3]],
    matrix: 'hedgerow_meadow',
    stone: 'limestone',
    building: ['light_stone', 'slate_roof'],
    farming: ['cereal', 'vineyard', 'maize', 'orchard'],
    trees: ['oak', 'chestnut', 'beech'],
  },
  {
    id: 'touraine',
    name: 'Touraine',
    anchors: [[0.7, 47.3]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'slate_roof'],
    farming: ['cereal', 'vineyard', 'sunflower', 'orchard'],
    trees: ['oak', 'scots_pine', 'chestnut'],
  },
  {
    id: 'sologne',
    name: 'Sologne',
    anchors: [[2.0, 47.6]],
    matrix: 'conifer_forest',
    stone: 'clay',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['fallow', 'maize', 'cereal'],
    trees: ['scots_pine', 'oak', 'birch'],
  },
  {
    id: 'berry',
    name: 'Champagne berrichonne',
    anchors: [[2.0, 46.9]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'sunflower', 'fallow'],
    trees: ['oak', 'hornbeam', 'ash'],
  },
  {
    id: 'vendee_bocage',
    name: 'Bocage vendéen',
    anchors: [[-1.0, 46.8]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['cereal', 'maize', 'sunflower', 'fallow'],
    trees: ['oak', 'chestnut', 'ash'],
  },
  {
    id: 'marais_poitevin',
    name: 'Marais poitevin',
    anchors: [[-0.8, 46.3]],
    matrix: 'marsh',
    stone: 'alluvium',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['ash', 'poplar', 'alder'],
  },
  {
    id: 'limousin',
    name: 'Limousin',
    anchors: [[1.6, 45.8], [2.2, 45.5]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['chestnut', 'oak', 'beech'],
  },
  {
    id: 'limagne',
    name: 'Limagne',
    anchors: [[3.2, 45.9]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['dark_stone', 'curved_tile_roof'],
    farming: ['cereal', 'maize', 'sunflower', 'vineyard'],
    trees: ['oak', 'poplar', 'ash'],
  },
  {
    id: 'volcans_auvergne',
    name: 'Volcans d’Auvergne',
    anchors: [[2.9, 45.5]],
    matrix: 'alpine_pasture',
    stone: 'basalt',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['beech', 'fir', 'spruce'],
  },
  {
    id: 'aubrac',
    name: 'Aubrac',
    anchors: [[3.0, 44.65]],
    matrix: 'alpine_pasture',
    stone: 'basalt',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['beech', 'ash', 'birch'],
  },
  {
    id: 'causses',
    name: 'Grands Causses',
    anchors: [[3.2, 44.2]],
    matrix: 'dry_steppe',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['black_pine', 'oak', 'juniper'],
  },
  {
    id: 'cevennes',
    name: 'Cévennes',
    anchors: [[3.7, 44.2]],
    matrix: 'terraced_slope',
    stone: 'schist',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['orchard', 'vineyard', 'fallow'],
    trees: ['chestnut', 'holm_oak', 'maritime_pine'],
  },
  {
    id: 'landes',
    name: 'Landes de Gascogne',
    anchors: [[-0.8, 44.3], [-1.1, 43.9]],
    matrix: 'conifer_forest',
    stone: 'alluvium',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['maize', 'fallow', 'cereal'],
    trees: ['maritime_pine', 'oak', 'birch'],
  },
  {
    id: 'bordelais',
    name: 'Bordelais',
    anchors: [[-0.5, 44.9]],
    matrix: 'broadleaf_woodland',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'cereal', 'maize', 'fallow'],
    trees: ['oak', 'maritime_pine', 'chestnut'],
  },
  {
    id: 'perigord',
    name: 'Périgord',
    anchors: [[0.9, 45.0]],
    matrix: 'broadleaf_woodland',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['orchard', 'cereal', 'maize', 'vineyard'],
    trees: ['oak', 'chestnut', 'juniper'],
  },
  {
    id: 'quercy',
    name: 'Quercy',
    anchors: [[1.5, 44.5]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['fallow', 'cereal', 'vineyard', 'orchard'],
    trees: ['oak', 'juniper', 'black_pine'],
  },
  {
    id: 'gascogne',
    name: 'Coteaux de Gascogne',
    anchors: [[0.6, 43.6]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['pale_brick', 'curved_tile_roof'],
    farming: ['maize', 'sunflower', 'cereal', 'fallow'],
    trees: ['oak', 'poplar', 'ash'],
  },
  {
    id: 'pays_basque',
    name: 'Pays basque',
    anchors: [[-1.3, 43.3]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['maize', 'fallow', 'cereal'],
    trees: ['oak', 'beech', 'chestnut'],
  },
  {
    id: 'pyrenees_centrales',
    name: 'Pyrénées centrales',
    anchors: [[0.5, 42.85], [-0.4, 42.95]],
    matrix: 'alpine_pasture',
    stone: 'granite',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['fir', 'beech', 'scots_pine'],
  },
  {
    id: 'corbieres',
    name: 'Corbières',
    anchors: [[2.6, 43.0]],
    matrix: 'garrigue',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'fallow', 'olive', 'orchard'],
    trees: ['holm_oak', 'aleppo_pine', 'juniper'],
  },
  {
    id: 'languedoc',
    name: 'Plaine du Languedoc',
    anchors: [[3.4, 43.5], [4.0, 43.7]],
    matrix: 'garrigue',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'orchard', 'fallow', 'olive'],
    trees: ['holm_oak', 'stone_pine', 'aleppo_pine'],
  },
  {
    id: 'camargue',
    name: 'Camargue',
    anchors: [[4.5, 43.5]],
    matrix: 'marsh',
    stone: 'alluvium',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['rice', 'fallow', 'cereal'],
    trees: ['ash', 'poplar', 'alder'],
  },
  {
    id: 'vallee_rhone',
    name: 'Vallée du Rhône',
    anchors: [[4.8, 44.6], [4.85, 45.1]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['orchard', 'vineyard', 'maize', 'fallow'],
    trees: ['stone_pine', 'poplar', 'oak'],
  },
  {
    id: 'provence_calcaire',
    name: 'Provence calcaire',
    anchors: [[5.6, 43.6]],
    matrix: 'garrigue',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'olive', 'orchard', 'lavender'],
    trees: ['holm_oak', 'aleppo_pine', 'stone_pine'],
  },
  {
    id: 'haute_provence',
    name: 'Haute-Provence',
    anchors: [[5.9, 44.05]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['lavender', 'cereal', 'orchard', 'fallow'],
    trees: ['black_pine', 'holm_oak', 'oak'],
  },
  {
    id: 'maures',
    name: 'Maures et Estérel',
    anchors: [[6.4, 43.3]],
    matrix: 'dry_scrub',
    stone: 'schist',
    building: ['rendered', 'curved_tile_roof'],
    farming: ['vineyard', 'orchard', 'olive'],
    trees: ['cork_oak', 'maritime_pine', 'chestnut'],
  },
  {
    id: 'vercors',
    name: 'Vercors et Chartreuse',
    anchors: [[5.5, 45.05]],
    matrix: 'conifer_forest',
    stone: 'limestone',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['fir', 'spruce', 'beech'],
  },
  {
    id: 'alpes_nord',
    name: 'Alpes du Nord',
    anchors: [[6.4, 45.5], [6.8, 45.9]],
    matrix: 'alpine_pasture',
    stone: 'limestone',
    building: ['timber', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['spruce', 'fir', 'beech'],
  },
  {
    id: 'alpes_sud',
    name: 'Alpes du Sud',
    anchors: [[6.5, 44.5]],
    matrix: 'bare_rock',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow', 'lavender', 'cereal'],
    trees: ['larch', 'black_pine', 'scots_pine'],
  },
  {
    id: 'corse',
    name: 'Corse',
    anchors: [[9.1, 42.3], [9.0, 41.8]],
    matrix: 'dry_scrub',
    stone: 'granite',
    building: ['rendered', 'curved_tile_roof'],
    farming: ['vineyard', 'orchard', 'olive', 'fallow'],
    trees: ['chestnut', 'holm_oak', 'maritime_pine'],
  },

  // --------------------------------------------------------------- Espagne --
  {
    id: 'rias_baixas',
    name: 'Rías Baixas',
    anchors: [[-8.7, 42.5]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'curved_tile_roof'],
    farming: ['vineyard', 'maize', 'fallow', 'orchard'],
    trees: ['oak', 'eucalyptus', 'maritime_pine'],
  },
  {
    id: 'galicia_interior',
    name: 'Galicia interior',
    anchors: [[-7.6, 42.75], [-7.5, 43.2]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['granite', 'stone_slab_roof'],
    farming: ['maize', 'fallow', 'cereal'],
    trees: ['oak', 'chestnut', 'maritime_pine'],
  },
  {
    id: 'asturias',
    name: 'Asturias',
    anchors: [[-5.9, 43.35], [-6.6, 43.4]],
    matrix: 'hedgerow_meadow',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['fallow', 'maize', 'orchard'],
    trees: ['oak', 'beech', 'chestnut'],
  },
  {
    id: 'picos_europa',
    name: 'Picos de Europa',
    anchors: [[-4.9, 43.18]],
    matrix: 'bare_rock',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['beech', 'oak', 'birch'],
  },
  {
    id: 'cantabria',
    name: 'Cantabria',
    anchors: [[-4.0, 43.33]],
    matrix: 'hedgerow_meadow',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['fallow', 'maize', 'orchard'],
    trees: ['oak', 'beech', 'eucalyptus'],
  },
  {
    id: 'pais_vasco',
    name: 'País Vasco',
    anchors: [[-2.5, 43.15]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['fallow', 'maize', 'orchard'],
    trees: ['oak', 'beech', 'chestnut'],
  },
  {
    id: 'navarra_media',
    name: 'Navarra media',
    anchors: [[-1.7, 42.6]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['cereal', 'vineyard', 'fallow', 'orchard'],
    trees: ['oak', 'holm_oak', 'scots_pine'],
  },
  {
    id: 'bardenas',
    name: 'Bardenas Reales',
    anchors: [[-1.45, 42.2]],
    matrix: 'desert_stone',
    stone: 'gypsum',
    building: ['light_stone', 'flat_roof'],
    farming: ['cereal', 'fallow'],
    trees: ['juniper', 'aleppo_pine'],
  },
  {
    id: 'rioja',
    name: 'La Rioja',
    anchors: [[-2.5, 42.4]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'cereal', 'orchard', 'fallow'],
    trees: ['holm_oak', 'oak', 'scots_pine'],
  },
  {
    id: 'pirineo_aragones',
    name: 'Pirineo aragonés',
    anchors: [[-0.3, 42.6]],
    matrix: 'alpine_pasture',
    stone: 'limestone',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['fir', 'scots_pine', 'beech'],
  },
  {
    id: 'pirineu_catala',
    name: 'Pirineu català',
    anchors: [[1.5, 42.4]],
    matrix: 'conifer_forest',
    stone: 'granite',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['fir', 'scots_pine', 'birch'],
  },
  {
    id: 'somontano',
    name: 'Somontano',
    anchors: [[0.1, 42.1]],
    matrix: 'dry_scrub',
    stone: 'sandstone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'olive', 'cereal', 'almond'],
    trees: ['holm_oak', 'aleppo_pine', 'juniper'],
  },
  {
    id: 'monegros',
    name: 'Los Monegros',
    anchors: [[-0.3, 41.6]],
    matrix: 'dry_steppe',
    stone: 'gypsum',
    building: ['light_stone', 'flat_roof'],
    farming: ['cereal', 'fallow', 'olive'],
    trees: ['aleppo_pine', 'juniper'],
  },
  {
    id: 'valle_ebro',
    name: 'Valle del Ebro',
    anchors: [[-0.9, 41.75]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['pale_brick', 'curved_tile_roof'],
    farming: ['orchard', 'maize', 'cereal', 'vineyard'],
    trees: ['poplar', 'aleppo_pine', 'olive'],
  },
  {
    id: 'emporda',
    name: 'Empordà',
    anchors: [[3.0, 42.2]],
    matrix: 'dry_scrub',
    stone: 'schist',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'olive', 'orchard', 'cereal'],
    trees: ['cork_oak', 'stone_pine', 'holm_oak'],
  },
  {
    id: 'penedes',
    name: 'Penedès',
    anchors: [[1.7, 41.4]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'olive', 'orchard', 'cereal'],
    trees: ['holm_oak', 'aleppo_pine', 'stone_pine'],
  },
  {
    id: 'delta_ebre',
    name: 'Delta de l’Ebre',
    anchors: [[0.7, 40.72]],
    matrix: 'marsh',
    stone: 'alluvium',
    building: ['whitewash', 'flat_roof'],
    farming: ['rice', 'orchard', 'fallow'],
    trees: ['poplar', 'stone_pine'],
  },
  {
    id: 'maestrazgo',
    name: 'Maestrazgo',
    anchors: [[-0.4, 40.5]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['olive', 'almond', 'cereal', 'fallow'],
    trees: ['black_pine', 'holm_oak', 'juniper'],
  },
  {
    id: 'huerta_valencia',
    name: 'Huerta de Valencia',
    anchors: [[-0.4, 39.4]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['orchard', 'rice', 'fallow', 'vineyard'],
    trees: ['stone_pine', 'palm', 'olive'],
  },
  {
    id: 'la_mancha',
    name: 'La Mancha',
    anchors: [[-3.2, 39.3], [-2.4, 39.0]],
    matrix: 'dry_steppe',
    stone: 'limestone',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['vineyard', 'cereal', 'olive', 'fallow'],
    trees: ['holm_oak', 'aleppo_pine', 'juniper'],
  },
  {
    id: 'montes_toledo',
    name: 'Montes de Toledo',
    anchors: [[-4.3, 39.5]],
    matrix: 'dry_scrub',
    stone: 'sandstone',
    building: ['dark_stone', 'curved_tile_roof'],
    farming: ['olive', 'cereal', 'fallow'],
    trees: ['holm_oak', 'cork_oak', 'juniper'],
  },
  {
    id: 'alcarria',
    name: 'La Alcarria',
    anchors: [[-2.7, 40.6]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['cereal', 'sunflower', 'lavender', 'fallow'],
    trees: ['holm_oak', 'black_pine', 'juniper'],
  },
  {
    id: 'serrania_cuenca',
    name: 'Serranía de Cuenca',
    anchors: [[-2.0, 40.2]],
    matrix: 'conifer_forest',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['black_pine', 'scots_pine', 'holm_oak'],
  },
  {
    id: 'guadarrama',
    name: 'Sierra de Guadarrama',
    anchors: [[-3.9, 40.8]],
    matrix: 'conifer_forest',
    stone: 'granite',
    building: ['granite', 'curved_tile_roof'],
    farming: ['fallow'],
    trees: ['scots_pine', 'holm_oak', 'oak'],
  },
  {
    id: 'tierra_campos',
    name: 'Tierra de Campos',
    anchors: [[-5.0, 42.0]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['adobe', 'curved_tile_roof'],
    farming: ['cereal', 'fallow', 'sunflower', 'vineyard'],
    trees: ['poplar', 'holm_oak', 'ash'],
  },
  {
    id: 'ribera_duero',
    name: 'Ribera del Duero',
    anchors: [[-3.7, 41.6]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['vineyard', 'cereal', 'fallow', 'sunflower'],
    trees: ['holm_oak', 'juniper', 'scots_pine'],
  },
  {
    id: 'bierzo',
    name: 'El Bierzo',
    anchors: [[-6.6, 42.6]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['vineyard', 'orchard', 'fallow', 'cereal'],
    trees: ['chestnut', 'oak', 'holm_oak'],
  },
  {
    id: 'arribes',
    name: 'Arribes del Duero',
    anchors: [[-6.5, 41.2]],
    matrix: 'dry_scrub',
    stone: 'granite',
    building: ['granite', 'curved_tile_roof'],
    farming: ['olive', 'vineyard', 'almond', 'fallow'],
    trees: ['holm_oak', 'cork_oak', 'juniper'],
  },
  {
    id: 'dehesa_extremena',
    name: 'Dehesa extremeña',
    anchors: [[-6.1, 39.2], [-6.3, 38.6]],
    matrix: 'dry_scrub',
    stone: 'granite',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['olive', 'cereal', 'fallow', 'orchard'],
    trees: ['holm_oak', 'cork_oak', 'olive'],
  },
  {
    id: 'gredos',
    name: 'Sierra de Gredos',
    anchors: [[-5.2, 40.3]],
    matrix: 'bare_rock',
    stone: 'granite',
    building: ['granite', 'stone_slab_roof'],
    farming: ['fallow', 'orchard'],
    trees: ['scots_pine', 'oak', 'chestnut'],
  },
  {
    id: 'la_vera',
    name: 'La Vera et Valle del Jerte',
    anchors: [[-5.7, 40.1]],
    matrix: 'terraced_slope',
    stone: 'granite',
    building: ['half_timber', 'curved_tile_roof'],
    farming: ['orchard', 'olive', 'vineyard', 'fallow'],
    trees: ['chestnut', 'oak', 'olive'],
  },
  {
    id: 'sierra_morena',
    name: 'Sierra Morena',
    anchors: [[-5.0, 38.3], [-3.5, 38.4]],
    matrix: 'dry_scrub',
    stone: 'schist',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['olive', 'cereal', 'fallow'],
    trees: ['holm_oak', 'cork_oak', 'juniper'],
  },
  {
    id: 'campina_guadalquivir',
    name: 'Campiña del Guadalquivir',
    anchors: [[-5.5, 37.5], [-4.6, 37.6]],
    matrix: 'openfield_cropland',
    stone: 'clay',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['olive', 'cereal', 'sunflower', 'orchard'],
    trees: ['olive', 'stone_pine', 'holm_oak'],
  },
  {
    id: 'donana',
    name: 'Doñana',
    anchors: [[-6.4, 37.0]],
    matrix: 'marsh',
    stone: 'alluvium',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['fallow', 'orchard', 'greenhouse'],
    trees: ['stone_pine', 'cork_oak', 'juniper'],
  },
  {
    id: 'olivar_jaen',
    name: 'Olivar de Jaén',
    anchors: [[-3.6, 37.8]],
    matrix: 'terraced_slope',
    stone: 'limestone',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['olive', 'cereal', 'orchard', 'fallow'],
    trees: ['olive', 'holm_oak', 'aleppo_pine'],
  },
  {
    id: 'cazorla',
    name: 'Sierras de Cazorla',
    anchors: [[-2.9, 37.9]],
    matrix: 'conifer_forest',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['olive', 'fallow'],
    trees: ['black_pine', 'aleppo_pine', 'holm_oak'],
  },
  {
    id: 'alpujarra',
    name: 'Alpujarra',
    anchors: [[-3.2, 36.95]],
    matrix: 'terraced_slope',
    stone: 'schist',
    building: ['whitewash', 'flat_roof'],
    farming: ['orchard', 'olive', 'almond', 'vineyard'],
    trees: ['chestnut', 'holm_oak', 'black_pine'],
  },
  {
    id: 'vega_granada',
    name: 'Vega de Granada',
    anchors: [[-3.65, 37.2]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['whitewash', 'curved_tile_roof'],
    farming: ['orchard', 'olive', 'maize', 'cereal'],
    trees: ['poplar', 'olive', 'stone_pine'],
  },
  {
    id: 'sierra_nevada',
    name: 'Sierra Nevada',
    anchors: [[-3.3, 37.1]],
    matrix: 'bare_rock',
    stone: 'schist',
    building: ['whitewash', 'flat_roof'],
    farming: ['fallow'],
    trees: ['black_pine', 'juniper', 'holm_oak'],
  },
  {
    id: 'tabernas',
    name: 'Desierto de Tabernas',
    anchors: [[-2.4, 37.05]],
    matrix: 'desert_stone',
    stone: 'gypsum',
    building: ['whitewash', 'flat_roof'],
    farming: ['orchard', 'almond', 'fallow'],
    trees: ['juniper', 'aleppo_pine'],
  },
  {
    id: 'campo_dalias',
    name: 'Campo de Dalías',
    anchors: [[-2.8, 36.78]],
    matrix: 'desert_stone',
    stone: 'limestone',
    building: ['whitewash', 'flat_roof'],
    farming: ['greenhouse', 'orchard', 'fallow'],
    trees: ['palm', 'juniper'],
  },
  {
    id: 'huerta_murcia',
    name: 'Huerta de Murcia',
    anchors: [[-1.2, 38.0]],
    matrix: 'dry_steppe',
    stone: 'limestone',
    building: ['whitewash', 'flat_roof'],
    farming: ['orchard', 'almond', 'vineyard', 'olive'],
    trees: ['stone_pine', 'aleppo_pine', 'palm'],
  },
  {
    id: 'mallorca',
    name: 'Mallorca',
    anchors: [[3.0, 39.6], [2.8, 39.75]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'curved_tile_roof'],
    farming: ['olive', 'almond', 'orchard', 'vineyard'],
    trees: ['holm_oak', 'aleppo_pine', 'olive'],
  },
  // --------------------------------------------------- Royaume-Uni ---------
  {
    id: 'weald',
    name: 'The Weald',
    anchors: [[0.3, 51.05]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['cereal', 'fallow', 'orchard', 'rapeseed'],
    trees: ['oak', 'hornbeam', 'beech'],
  },
  {
    id: 'london_basin',
    name: 'London Basin',
    anchors: [[-0.15, 51.5]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'fallow', 'rapeseed'],
    trees: ['oak', 'ash', 'hornbeam'],
  },
  {
    id: 'north_downs',
    name: 'North Downs',
    anchors: [[0.0, 51.25]],
    matrix: 'broadleaf_woodland',
    stone: 'chalk',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'ash', 'oak'],
  },
  {
    id: 'south_downs',
    name: 'South Downs',
    anchors: [[-0.55, 50.9]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'ash', 'hornbeam'],
  },
  {
    id: 'romney_marsh',
    name: 'Romney Marsh',
    anchors: [[0.85, 50.98]],
    matrix: 'wet_grassland',
    stone: 'alluvium',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['alder', 'ash', 'poplar'],
  },
  {
    id: 'chilterns',
    name: 'Chilterns',
    anchors: [[-0.75, 51.7]],
    matrix: 'broadleaf_woodland',
    stone: 'chalk',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'oak', 'ash'],
  },
  {
    id: 'new_forest',
    name: 'New Forest',
    anchors: [[-1.6, 50.87]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['red_brick', 'thatch_roof'],
    farming: ['fallow'],
    trees: ['oak', 'beech', 'scots_pine'],
  },
  {
    id: 'salisbury_plain',
    name: 'Salisbury Plain',
    anchors: [[-1.9, 51.2]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'ash', 'hornbeam'],
  },
  {
    id: 'cotswolds',
    name: 'Cotswolds',
    anchors: [[-2.0, 51.85]],
    matrix: 'openfield_cropland',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'ash', 'oak'],
  },
  {
    id: 'somerset_levels',
    name: 'Somerset Levels',
    anchors: [[-2.85, 51.1]],
    matrix: 'wet_grassland',
    stone: 'alluvium',
    building: ['light_stone', 'flat_tile_roof'],
    farming: ['fallow', 'orchard', 'cereal'],
    trees: ['alder', 'poplar', 'ash'],
  },
  {
    id: 'mendip',
    name: 'Mendip Hills',
    anchors: [[-2.7, 51.28]],
    matrix: 'dry_scrub',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['ash', 'hornbeam', 'oak'],
  },
  {
    id: 'devon',
    name: 'Devon',
    anchors: [[-3.8, 50.8], [-4.2, 51.0]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['rendered', 'thatch_roof'],
    farming: ['fallow', 'cereal', 'orchard'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'dartmoor',
    name: 'Dartmoor',
    anchors: [[-3.9, 50.58]],
    matrix: 'moor_heath',
    stone: 'granite',
    building: ['granite', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'scots_pine'],
  },
  {
    id: 'exmoor',
    name: 'Exmoor',
    anchors: [[-3.7, 51.13]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'ash'],
  },
  {
    id: 'cornwall',
    name: 'Cornwall',
    anchors: [[-5.0, 50.35], [-4.6, 50.45]],
    matrix: 'hedgerow_meadow',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['oak', 'ash', 'maritime_pine'],
  },
  {
    id: 'dorset',
    name: 'Dorset',
    anchors: [[-2.35, 50.8]],
    matrix: 'hedgerow_meadow',
    stone: 'chalk',
    building: ['light_stone', 'thatch_roof'],
    farming: ['cereal', 'fallow', 'orchard'],
    trees: ['beech', 'ash', 'oak'],
  },
  {
    id: 'fens',
    name: 'The Fens',
    anchors: [[0.15, 52.55]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'maize'],
    trees: ['poplar', 'ash', 'alder'],
  },
  {
    id: 'east_anglia',
    name: 'East Anglian Heights',
    anchors: [[0.9, 52.15]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'sunflower'],
    trees: ['oak', 'ash', 'hornbeam'],
  },
  {
    id: 'breckland',
    name: 'Breckland',
    anchors: [[0.7, 52.45]],
    matrix: 'conifer_forest',
    stone: 'sandstone',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'fallow', 'rapeseed'],
    trees: ['scots_pine', 'birch', 'oak'],
  },
  {
    id: 'norfolk_broads',
    name: 'Norfolk Broads',
    anchors: [[1.55, 52.68]],
    matrix: 'marsh',
    stone: 'alluvium',
    building: ['red_brick', 'thatch_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['alder', 'poplar', 'birch'],
  },
  {
    id: 'lincolnshire_wolds',
    name: 'Lincolnshire Wolds',
    anchors: [[-0.2, 53.4]],
    matrix: 'openfield_cropland',
    stone: 'chalk',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['ash', 'beech', 'oak'],
  },
  {
    id: 'midlands',
    name: 'English Midlands',
    anchors: [[-1.5, 52.55], [-1.0, 52.9]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'fallow', 'rapeseed', 'maize'],
    trees: ['oak', 'ash', 'hornbeam'],
  },
  {
    id: 'welsh_marches',
    name: 'Welsh Marches',
    anchors: [[-2.85, 52.35]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['fallow', 'cereal', 'orchard'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'peak_district',
    name: 'Peak District',
    anchors: [[-1.8, 53.3]],
    matrix: 'moor_heath',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'ash'],
  },
  {
    id: 'cheshire_plain',
    name: 'Cheshire Plain',
    anchors: [[-2.5, 53.2]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['half_timber', 'flat_tile_roof'],
    farming: ['fallow', 'maize', 'cereal'],
    trees: ['oak', 'ash', 'alder'],
  },
  {
    id: 'lancashire_plain',
    name: 'Lancashire Plain',
    anchors: [[-2.55, 53.5], [-2.85, 53.75]],
    matrix: 'hedgerow_meadow',
    stone: 'clay',
    building: ['red_brick', 'slate_roof'],
    farming: ['fallow', 'cereal', 'maize'],
    trees: ['oak', 'ash', 'alder'],
  },
  {
    id: 'south_pennines',
    name: 'South Pennines',
    anchors: [[-2.0, 53.7]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow'],
    trees: ['birch', 'oak', 'scots_pine'],
  },
  {
    id: 'yorkshire_dales',
    name: 'Yorkshire Dales',
    anchors: [[-2.15, 54.2]],
    matrix: 'moor_heath',
    stone: 'limestone',
    building: ['light_stone', 'stone_slab_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['ash', 'birch', 'oak'],
  },
  {
    id: 'north_york_moors',
    name: 'North York Moors',
    anchors: [[-0.9, 54.4]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'flat_tile_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['birch', 'oak', 'scots_pine'],
  },
  {
    id: 'vale_of_york',
    name: 'Vale of York',
    anchors: [[-1.1, 54.0]],
    matrix: 'openfield_cropland',
    stone: 'alluvium',
    building: ['red_brick', 'flat_tile_roof'],
    farming: ['cereal', 'rapeseed', 'fallow', 'maize'],
    trees: ['oak', 'ash', 'poplar'],
  },
  {
    id: 'lake_district',
    name: 'Lake District',
    anchors: [[-3.1, 54.5]],
    matrix: 'moor_heath',
    stone: 'schist',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'spruce'],
  },
  {
    id: 'northumberland',
    name: 'Northumberland',
    anchors: [[-2.0, 55.25]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['scots_pine', 'birch', 'spruce'],
  },
  {
    id: 'snowdonia',
    name: 'Snowdonia',
    anchors: [[-3.9, 53.05]],
    matrix: 'moor_heath',
    stone: 'schist',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'spruce'],
  },
  {
    id: 'mid_wales',
    name: 'Mid Wales',
    anchors: [[-3.6, 52.4]],
    matrix: 'moor_heath',
    stone: 'schist',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['oak', 'birch', 'spruce'],
  },
  {
    id: 'brecon_beacons',
    name: 'Brecon Beacons',
    anchors: [[-3.45, 51.88]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'ash'],
  },
  {
    id: 'pembrokeshire',
    name: 'Pembrokeshire',
    anchors: [[-4.9, 51.85]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['oak', 'ash', 'alder'],
  },
  {
    id: 'vale_of_glamorgan',
    name: 'Vale of Glamorgan',
    anchors: [[-3.45, 51.45]],
    matrix: 'hedgerow_meadow',
    stone: 'limestone',
    building: ['light_stone', 'slate_roof'],
    farming: ['cereal', 'fallow', 'rapeseed'],
    trees: ['oak', 'ash', 'beech'],
  },
  {
    id: 'scottish_borders',
    name: 'Scottish Borders',
    anchors: [[-2.8, 55.6]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['spruce', 'birch', 'scots_pine'],
  },
  {
    id: 'lothian',
    name: 'Lothian',
    anchors: [[-3.0, 55.92]],
    matrix: 'openfield_cropland',
    stone: 'sandstone',
    building: ['light_stone', 'slate_roof'],
    farming: ['cereal', 'rapeseed', 'fallow'],
    trees: ['beech', 'ash', 'scots_pine'],
  },
  {
    id: 'galloway',
    name: 'Galloway',
    anchors: [[-4.3, 55.0]],
    matrix: 'moor_heath',
    stone: 'granite',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['spruce', 'birch', 'oak'],
  },
  {
    id: 'central_belt',
    name: 'Central Belt',
    anchors: [[-4.0, 55.85]],
    matrix: 'hedgerow_meadow',
    stone: 'sandstone',
    building: ['light_stone', 'slate_roof'],
    farming: ['fallow', 'cereal', 'rapeseed'],
    trees: ['ash', 'oak', 'birch'],
  },
  {
    id: 'trossachs',
    name: 'Trossachs',
    anchors: [[-4.4, 56.3]],
    matrix: 'conifer_forest',
    stone: 'schist',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['oak', 'birch', 'spruce'],
  },
  {
    id: 'grampians',
    name: 'Grampian Highlands',
    anchors: [[-4.1, 56.85]],
    matrix: 'bare_rock',
    stone: 'granite',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['scots_pine', 'birch', 'spruce'],
  },
  {
    id: 'cairngorms',
    name: 'Cairngorms',
    anchors: [[-3.6, 57.1]],
    matrix: 'bare_rock',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['fallow'],
    trees: ['scots_pine', 'birch', 'juniper'],
  },
  {
    id: 'aberdeenshire',
    name: 'Aberdeenshire',
    anchors: [[-2.4, 57.3]],
    matrix: 'openfield_cropland',
    stone: 'granite',
    building: ['granite', 'slate_roof'],
    farming: ['cereal', 'fallow', 'rapeseed'],
    trees: ['scots_pine', 'birch', 'beech'],
  },
  {
    id: 'moray',
    name: 'Moray',
    anchors: [[-3.4, 57.55]],
    matrix: 'conifer_forest',
    stone: 'sandstone',
    building: ['light_stone', 'slate_roof'],
    farming: ['cereal', 'fallow', 'rapeseed'],
    trees: ['scots_pine', 'birch', 'spruce'],
  },
  {
    id: 'northwest_highlands',
    name: 'North West Highlands',
    anchors: [[-5.2, 57.6], [-5.0, 58.1]],
    matrix: 'moor_heath',
    stone: 'schist',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['birch', 'scots_pine', 'juniper'],
  },
  {
    id: 'caithness',
    name: 'Caithness et Sutherland',
    anchors: [[-3.8, 58.4]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['birch', 'juniper'],
  },
  {
    id: 'skye',
    name: 'Skye et Hébrides intérieures',
    anchors: [[-6.3, 57.4]],
    matrix: 'moor_heath',
    stone: 'basalt',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['birch', 'juniper'],
  },
  {
    id: 'outer_hebrides',
    name: 'Outer Hebrides',
    anchors: [[-7.2, 57.8]],
    matrix: 'dune_coast',
    stone: 'granite',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['birch', 'juniper'],
  },
  {
    id: 'orkney',
    name: 'Orkney et Shetland',
    anchors: [[-2.9, 59.0], [-1.3, 60.3]],
    matrix: 'moor_heath',
    stone: 'sandstone',
    building: ['dark_stone', 'stone_slab_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['birch', 'juniper'],
  },
  {
    id: 'antrim',
    name: 'Antrim',
    anchors: [[-6.2, 55.0]],
    matrix: 'moor_heath',
    stone: 'basalt',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['birch', 'ash', 'spruce'],
  },
  {
    id: 'ulster_drumlins',
    name: 'Ulster',
    anchors: [[-6.8, 54.4]],
    matrix: 'hedgerow_meadow',
    stone: 'schist',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow', 'cereal'],
    trees: ['ash', 'oak', 'alder'],
  },
  {
    id: 'fermanagh',
    name: 'Fermanagh',
    anchors: [[-7.6, 54.35]],
    matrix: 'wet_grassland',
    stone: 'limestone',
    building: ['whitewash', 'slate_roof'],
    farming: ['fallow'],
    trees: ['ash', 'alder', 'oak'],
  },
];
